apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devopsareej
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: areejbs/spring-app:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_APPLICATION_NAME
              value: TPCafe_Areejbensalah
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/cafe_db?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: cafe
            - name: SPRING_DATASOURCE_PASSWORD
              value: cafe123
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQL8Dialect
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devopsareej
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088
